#!/bin/bash

#Check if a URL has been set after recon command.
if [ -d $1 ]; then
    echo 'Please provide a domain: recon example.com'
    exit 1
fi

export URL=$(echo $1)

    #Opens $URL in Sublist3r
    echo 'Starting Sublist3r on' $URL
    if [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then 
		python ~/Sublist3r/sublist3r.py -d "$URL" -o domainsfile.txt
	elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW32_NT" ]; then # Probably needs tweaking
		python ~/Sublist3r/sublist3r.py -d "$URL" -o domainsfile.txt
	elif [ "$(expr substr $(uname -s) 1 10)" == "MINGW64_NT" ]; then # Probably needs tweaking
		python ~/Sublist3r/sublist3r.py -d "$URL" -o domainsfile.txt
	elif [ "$(uname)" == "Darwin" ]; then # Probably needs tweaking
		python ~/Sublist3r/sublist3r.py -d "$URL" -o domainsfile.txt
    exit 1
fi

if [ -e domainsfile.txt ];then
	echo 'Sublist3r Scan complete, checking which domains resolve..'
	while read domain; 
	do if host "$domain" > /dev/null; 
	then echo $domain; 
	fi; 
	done < domainsfile.txt >> resolveddomains.txt
	echo 'Resolved domains written to resolveddomains.txt'
	sleep 1
fi

if [ -e resolveddomains.txt ];then
	echo 'Starting webscreenshot on' $URL # requires PhantomJS & webscreenshot
	python ~/webscreenshot/webscreenshot.py -i resolveddomains.txt
	sleep 1
fi

if [ -d screenshots ];then
	# keypressed, read 1 char from stdin using dd
	# works using any sh-shell
	readkbd(){
		stty -icanon -echo
		dd bs=1 count=1 2>/dev/null
		stty icanon echo
	}

while printf "Run eog on screenshots:N\b" # default N to continue script
	  response=$(readkbd)
	  printf "\r				\n"
	  case "$response" in
	  			Y|y) response="Y" ;; 
				n|N|"") response="N" ;; # default = ENTER
				*) response="N"	;;
	  esac
	  [ "$response" = "Y" ]
do
				echo "Using eog to open screenshots directory"
				eog screenshots
				done
				echo 'All done.'
fi


export SCRIPT=$(python3 ~/dirsearch/dirsearch.py)

if [ -e resolveddomains.txt ];then
	echo 'Starting dirsearch on resolved domains'
	python3 ~/dirsearch/dirsearch.py -u . <(cat resolveddomains.txt | awk '{print "$SCRIPT -e *"}')
fi